// Code generated by command: go run calcAttacks.go -out attacks.s -stubs attackstub.go. DO NOT EDIT.

package bitflip

func CalcAttacks(occupied uint64, location uint64, angles [4]uint64) (uint64, uint64)
