// Code generated by command: go run calcAttacks.go -out attacks_amd64.s -stubs attacks_amd64.go. DO NOT EDIT.

package bitflip

func queenAttacks(occupied uint64, location uint64, rank uint64, file uint64, diag uint64, antidiag uint64) uint64

func bishopRookAttacks(occupied uint64, location uint64, rankOrDiag uint64, fileOrAntiDiag uint64) uint64
