// Code generated by command: go run bitflipavo.go -out bitflip_amd64.s -stubs bitflip_amd64.go. DO NOT EDIT.

package bitflip

// Flips the bytes in x, MSB->LSB and vice-versa
func Reverse64AVX(x uint64) uint64
