// Code generated by command: go run bitflipavo.go -out bitflip_amd64.s -stubs bitflip_amd64.go. DO NOT EDIT.

#include "textflag.h"

DATA bytes<>+0(SB)/8, $0x0f0f0f0f0f0f0f0f
DATA bytes<>+8(SB)/8, $0x0f0f0f0f0f0f0f0f
DATA bytes<>+16(SB)/8, $0x0e060a020c040800
DATA bytes<>+24(SB)/8, $0x0f070b030d050901
DATA bytes<>+32(SB)/8, $0xe060a020c0408000
DATA bytes<>+40(SB)/8, $0xf070b030d0509010
GLOBL bytes<>(SB), RODATA|NOPTR, $48

// func Reverse64AVX(x uint64) uint64
// Requires: AVX, SSE, SSE2
TEXT ·Reverse64AVX(SB), NOSPLIT, $0-16
	MOVQ    x+0(FP), AX
	MOVQ    AX, X0
	LEAQ    bytes<>+0(SB), AX
	MOVQ    $0x0001020304050607, CX
	MOVQ    $0x08090a0b0c0d0e0f, DX
	MOVQ    DX, X1
	MOVLHPS X1, X1
	MOVQ    CX, X1
	MOVAPD  (AX), X2
	MOVAPD  16(AX), X3
	MOVAPD  32(AX), X4
	VPAND   X2, X0, X5
	VPANDN  X0, X2, X0
	VPSRLD  $0x04, X0, X0
	VPSHUFB X5, X4, X5
	VPSHUFB X0, X3, X0
	VPOR    X0, X5, X0
	VPSHUFB X1, X0, X0
	MOVQ    X0, AX
	MOVQ    AX, ret+8(FP)
	RET
